"""initial_schema

Revision ID: e4347e76b746
Revises: 
Create Date: 2026-07-16 12:22:33.909185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4347e76b746'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_source', 'documents', ['source'], unique=False)
    op.create_index('ix_documents_uploaded_at', 'documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('google_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_credentials_user_id'), 'google_credentials', ['user_id'], unique=True)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('related_document', sa.String(), nullable=True),
    sa.Column('related_memory', sa.String(), nullable=True),
    sa.Column('related_graph_node', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_created_at', 'timeline_events', ['created_at'], unique=False)
    op.create_index('ix_timeline_events_event_type', 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_user_id'), 'timeline_events', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.drop_table('memory_nodes')
    op.drop_table('memory_edges')
    op.add_column('graph_edges', sa.Column('source_id', sa.String(), nullable=False))
    op.add_column('graph_edges', sa.Column('target_id', sa.String(), nullable=False))
    op.add_column('graph_edges', sa.Column('strength', sa.Float(), nullable=True))
    op.add_column('graph_edges', sa.Column('access_count', sa.Integer(), nullable=True))
    op.add_column('graph_edges', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    op.alter_column('graph_edges', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('graph_edges', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('graph_edges', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_graph_edges_source_id'), 'graph_edges', ['source_id'], unique=False)
    op.create_index('ix_graph_edges_source_target', 'graph_edges', ['source_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_id'), 'graph_edges', ['target_id'], unique=False)
    op.create_index('ix_graph_edges_type', 'graph_edges', ['type'], unique=False)
    op.drop_constraint(None, 'graph_edges', type_='foreignkey')
    op.drop_constraint(None, 'graph_edges', type_='foreignkey')
    op.create_foreign_key(None, 'graph_edges', 'graph_nodes', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'graph_edges', 'graph_nodes', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_column('graph_edges', 'source_node_id')
    op.drop_column('graph_edges', 'target_node_id')
    op.add_column('graph_nodes', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('graph_nodes', sa.Column('importance', sa.Float(), nullable=True))
    op.add_column('graph_nodes', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('graph_nodes', sa.Column('access_count', sa.Integer(), nullable=True))
    op.add_column('graph_nodes', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    op.alter_column('graph_nodes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('graph_nodes', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('ix_graph_nodes_importance', 'graph_nodes', ['importance'], unique=False)
    op.create_index('ix_graph_nodes_name', 'graph_nodes', ['name'], unique=False)
    op.create_index('ix_graph_nodes_type', 'graph_nodes', ['type'], unique=False)
    op.create_index(op.f('ix_graph_nodes_user_id'), 'graph_nodes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'graph_nodes', 'users', ['user_id'], ['id'])
    op.alter_column('memories', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('memories', 'chat_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('memories', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'default'"))
    op.alter_column('memories', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('memories', 'importance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('memories', 'recency',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('memories', 'last_accessed',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('memories', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('memories', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('ix_memories_chat_id', 'memories', ['chat_id'], unique=False)
    op.create_index('ix_memories_importance', 'memories', ['importance'], unique=False)
    op.create_index('ix_memories_type', 'memories', ['type'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index('ix_memories_type', table_name='memories')
    op.drop_index('ix_memories_importance', table_name='memories')
    op.drop_index('ix_memories_chat_id', table_name='memories')
    op.alter_column('memories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memories', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memories', 'last_accessed',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('memories', 'recency',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('memories', 'importance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('memories', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memories', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'default'"))
    op.alter_column('memories', 'chat_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memories', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'graph_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_graph_nodes_user_id'), table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_type', table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_name', table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_importance', table_name='graph_nodes')
    op.alter_column('graph_nodes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_nodes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('graph_nodes', 'last_accessed')
    op.drop_column('graph_nodes', 'access_count')
    op.drop_column('graph_nodes', 'metadata_json')
    op.drop_column('graph_nodes', 'importance')
    op.drop_column('graph_nodes', 'user_id')
    op.add_column('graph_edges', sa.Column('target_node_id', sa.TEXT(), nullable=False))
    op.add_column('graph_edges', sa.Column('source_node_id', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'graph_edges', type_='foreignkey')
    op.drop_constraint(None, 'graph_edges', type_='foreignkey')
    op.create_foreign_key(None, 'graph_edges', 'graph_nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'graph_edges', 'graph_nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_graph_edges_type', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_source_target', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_id'), table_name='graph_edges')
    op.alter_column('graph_edges', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_edges', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('graph_edges', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('graph_edges', 'last_accessed')
    op.drop_column('graph_edges', 'access_count')
    op.drop_column('graph_edges', 'strength')
    op.drop_column('graph_edges', 'target_id')
    op.drop_column('graph_edges', 'source_id')
    op.create_table('memory_edges',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('memory_id', sa.TEXT(), nullable=False),
    sa.Column('edge_id', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['graph_edges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'edge_id')
    )
    op.create_table('memory_nodes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('memory_id', sa.TEXT(), nullable=False),
    sa.Column('node_id', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'node_id')
    )
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_timeline_events_user_id'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_event_type', table_name='timeline_events')
    op.drop_index('ix_timeline_events_created_at', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_google_credentials_user_id'), table_name='google_credentials')
    op.drop_table('google_credentials')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index('ix_documents_uploaded_at', table_name='documents')
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
